spring:
  application:
    name: FairFree

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fairfree}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update        # Automatically update tables during development
    show-sql: true            # Show SQL queries in logs
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
#      mode: always
      mode: never
      platform: postgres
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_USERNAME:EMAIL_ID}
    password: ${MAIL_PASSWORD:EMAIL_PASSWORD}
    protocol: smtps
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtps.ssl.trust: smtp.gmail.com

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    apiversion:
      use:
        path-segment: 1

# AWS S3 Credentials
# Access and Secret Key are injected with as env variables.
aws:
  region: us-east-1
  s3:
    bucket: fairfree-item-images
  accessKey: ${AWS_ACCESS_KEY:YOUR_VALID_KEY}
  secretKey: ${AWS_SECRET_KEY:YOUR_VALID_KEY}

server:
  port: 8080

fairfree:
    jwt:
      secret:
          key: secret-key-for-generating-jwt-for-fairfree-app-access
      access-token:
        expiration: 36000000 # 10 hours
      refresh-token:
        expiration: 2592000000 # 30 days

# Logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: info #debug
    org.flywaydb: DEBUG

notification:
  items:
    expiring-days: 5 # 5 days

# configuration for health / metrics
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
