#Scrap metrics from /actuator/prometheus on regular interval from specified port.
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-boot-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["fairfree-app:8080"]
      #- targets: ["host.docker.internal:8080"]
